---
title: "R Notebook"
output: html_notebook
---


```{r}
Candidate = "TRUMP"
require(sp)

library(sp)
library(rgdal)
library(RColorBrewer)
library(spdep)
library(lattice)
library(latticeExtra)
library(maptools)
library(tmap)
library(spgwr)
library(GWmodel)

#prevents lat long rounding
options("scipen" = 100)
setwd("C:/Temp/FINAL_INPUTS/Box Sync/R/v4/GWR/GWR_Analysis")
```

```{r}
#reads in Countylayer
co = readOGR(dsn = getwd(),layer = "NY_CNTY",integer64="warn.loss")
df_co = data.frame(co)
spdf_co = SpatialPolygonsDataFrame(co,df_co)

d3 <- read.table("C:/Temp/FINAL_INPUTS/Box Sync/R/v4/v3_AllTags_002_AllSources_analysis_v3_310.csv",
                 header=TRUE, sep=",", na.strings="0", dec=".", strip.white=TRUE)
d3$PopDens <- log(d3$TotPop/d3$SqMiles)
d3$perc_white_comb <- d3$White_and_combination/d3$TotPop
d3$perc_white <- d3$White_only/d3$TotPop
d3$perc_Fem <- d3$FemOver18/d3$PopOver18
#Sorts etc
sp = spdf_co[order(spdf_co$NAME), ]
d3j = d3[order(d3$County), ]

#THis is a dumb intermediate
df1 <- data.frame(d3j[ which(d3j$CANDIDATE==Candidate), ])
outvar = "C:/Temp/FINAL_INPUTS/Box Sync/R/v4/v3_AllTags_002_AllSources_analysis_v3_310_subset.csv"
write.csv(df1,outvar,na="NA")


df = read.table(outvar,header=TRUE, sep=",", na.strings=0, dec=".",strip.white=TRUE)
spdf_co2 = merge(sp,df,by=(intersect(by.x,by.y)),by.x = "NAME", by.y = "County")

DeVar = "Candidate_VS"
InDeVar= c("Perc_BachelorsDeg_and_higher","perc_Fem","perc_white","PopDens", "MedianAge_Total") #,  "Candidate_TS17", "Candidate_TS18", "Candidate_TS19b4")


model.sel <- gwr.model.selection(DeVar,InDeVar, data=spdf_co2,bw=80,approach="aic",
               adaptive=T,kernel="bisquare",dMat=NULL,p=2, theta=0, longlat=F)
model.list <- model.sel[[1]]
gwr.model.view(DeVar, InDeVar, model.list)

plot(model.sel[[2]][,4], col = "black", pch = 20, lty = 5, 
	main = "Alternative view of GWR model selection procedure", 
	ylab = "AICc", xlab = "Model number", type = "b")



ruler.vector <- model.sel[[2]][,3]
lvar <- length(InDeVar)

sorted.models <- GWmodel::gwr.model.sort(model.sel,lvar, ruler.vector)

model.list <- sorted.models[[1]]
gwr.model.view(DeVar, InDeVar, model.list)
#bandwidth, AIC, AICc, RSS
model.sel[[2]] 

plot(sorted.models[[2]][,2], col = "black", pch = 20, lty = 5, 
	main = "Alternative view of GWR model selection procedure", 
	ylab = "AICc", xlab = "Model number", type = "b")

```


