---
title: "R Notebook"
output: html_notebook
---

```{r}
#install.packages("spdplyr")
require(sp)

library(sp)
library(rgdal)
library(RColorBrewer)
library(spdep)
#library(lattice)
#library(latticeExtra)
#library(maptools)
library(tmap)
#library(spgwr)
library(GWmodel)
library(geojsonio)
library(spdplyr)
library(rmapshaper)
#prevents lat long rounding
options("scipen" = 100)
setwd("C:/Temp/FINAL_INPUTS/Box Sync/R/v4/GWR/GWR_Analysis")
```

```{r}
Candidate = "TRUMP"
#reads in Countylayer  - WGS1984 - geographic Coordinate system
co = readOGR(dsn = getwd(),layer = "NY_CNTY",integer64="warn.loss")
df_co = data.frame(co)
spdf_co = SpatialPolygonsDataFrame(co,df_co)

d3 <- read.table("C:/Temp/FINAL_INPUTS/Box Sync/R/v4/v3_AllTags_002_AllSources_analysis_v3_310.csv",
                 header=TRUE, sep=",", na.strings="NA", dec=".", strip.white=TRUE)
d3$PopDens <- log(d3$TotPop/d3$SqMiles)
d3$perc_white_comb <- d3$White_and_combination/d3$TotPop
d3$perc_white <- d3$White_only/d3$TotPop
d3$perc_Fem <- d3$FemOver18/d3$PopOver18

#Sorts etc
sp = spdf_co[order(spdf_co$NAME), ]
d3j = d3[order(d3$County), ]

#THis is a dumb intermediate
df1 <- data.frame(d3j[ which(d3j$CANDIDATE==Candidate), ])
outvar = "C:/Temp/FINAL_INPUTS/Box Sync/R/v4/v3_AllTags_002_AllSources_analysis_v3_310_subset.csv"
write.csv(df1,outvar,na="0")


df = read.table(outvar,header=TRUE, sep=",", na.strings="NA", dec=".",strip.white=TRUE)
spdf_co2 = merge(sp,df,by=(intersect(by.x,by.y)),by.x = "NAME", by.y = "County")

DeVar = "Candidate_VS"
InDeVar= c("perc_white", "Candidate_TS17", "Candidate_TS18", "Candidate_TS19b4","Candidate_TS_b4") #, "Candidate_TS17", "Candidate_TS18", "Candidate_TS19b4","Perc_BachelorsDeg_and_higher","perc_Fem","perc_white","PopDens","MedianAge_Total",

model.sel <- gwr.model.selection(DeVar,InDeVar, data=spdf_co2,bw=26,approach="aic", adaptive=T,kernel="bisquare",dMat=NULL,p=2, theta=0, longlat=T)
model.list <- model.sel[[1]]
gwr.model.view(DeVar, InDeVar, model.list)

#add variable for method and data to plot.
column = 2
plot(model.sel[[2]][,column], col = "black", pch = 20, lty = 5, 
	main = "Alternative view of GWR model selection procedure", 
	ylab = "AICc", xlab = "Model number", type = "b")

ruler.vector <- model.sel[[2]][,column]
lvar <- length(InDeVar)

sorted.models <- gwr.model.sort(model.sel,lvar, ruler.vector)

model.list <- sorted.models[[1]]
gwr.model.view(DeVar, InDeVar, model.list)
#bandwidth, AIC, AICc, RSS
model.sel[[2]] 

plot(sorted.models[[2]][,column], col = "black", pch = 20, lty = 5, 
	main = "Alternative view of GWR model selection procedure", 
	ylab = "AICc", xlab = "Model number", type = "b")

sorted.models[[2]][,column]
sorted.models[[1]]

```

The below comes from the code example on p.7 of the GWModel Documentation.
See p.27 on Collinearity...

```{r bandwidth selection}
DM <- gw.dist(dp.locat = coordinates(spdf_co2))
```

```{r}
x = spdf_co2$Perc_BachelorsDeg_and_higher
y = "Perc_BachelorsDeg_and_higher"

lm.global <- lm(Candidate_VS~x, data = spdf_co2)
summary(lm.global)
#Candidate_TS18+Candidate_TS19b4+Candidate_TS17+Candidate_TS_b4+Perc_BachelorsDeg_and_higher+PopDens+perc_Fem+perc_white+MedianAge_Total
#Candidate_TS18+Candidate_TS19b4+Candidate_TS17+Candidate_TS_b4+Perc_BachelorsDeg_and_higher+PopDens+perc_Fem+perc_white+MedianAge_Total

bw.gwr.1 <- bw.gwr(Candidate_VS~x, data = spdf_co2, approach = "AICc",
	kernel = "bisquare", adaptive = TRUE, longlat = TRUE)
bw.gwr.2 <- bw.gwr(Candidate_VS~x, data = spdf_co2, approach = "cv",
	kernel = "bisquare", adaptive = TRUE)
bw.gwr.1
bw.gwr.2

#Model Selection

model.sel <- model.selection.gwr(DeVar ,InDeVar, data = spdf_co2, 
kernel = "bisquare", adaptive = TRUE, bw = 30) 
sorted.models <- model.sort.gwr(model.sel, numVars = length(InDeVar), 
ruler.vector = model.sel[[2]][,2]) 
model.list <- sorted.models[[1]]
model.list
model.view.gwr(DeVar, InDeVar, model.list = model.list)
model.sel

plot(sorted.models[[2]][,3], col = "black", pch = 20, lty = 5, 
	main = "Alternative view of GWR model selection procedure", 
	ylab = "AICc", xlab = "Model number", type = "b")


gwr.res <- gwr.basic(Candidate_VS~x,
                     data = spdf_co2, bw = bw.gwr.1, kernel = "bisquare", adaptive = TRUE, F123.test = FALSE)
#Writes out GWR results
writeGWR(gwr.res)

sdf <- gwr.res$SDF
char = "_TV"
colm = colnames(sdf@data)[grepl(char, colnames(sdf@data))]
setwd("C:/Temp/FINAL_INPUTS/Box Sync/R/v4/GWR/GWR_Analysis/Results_Bivariate/Images")
suffix = paste("_",y)

for (i in colm)
{
map = tm_shape(sdf) +tm_fill(col = i, breaks = c(-Inf,-4, -2.00,-1.67, 0, 1.67, 2.00, 4, Inf)) +  tm_legend(outside = FALSE, text.size = .8)
print(map)
save_tmap(tm = map, filename = paste(i,suffix,".png",sep = ''))

}
r2 = tm_shape(sdf) +tm_fill(col = "Local_R2") +  tm_legend(outside = FALSE, text.size = .8)
save_tmap(tm = r2, filename = paste("r2",suffix,".png",sep = ''))
r2
```



```{r for original Program}
#OUtput
writeGWR(gwr.res)
sdf <- gwr.res$SDF
colm0 <- names(gwr.res$SDF)
sdfexport <- gwr.res$SDF

sdfexport <- sdfexport %>% rename(Intrcpt = Intercept)
sdfexport <- sdfexport %>% rename(TS19b4 = Candidate_TS19b4)
sdfexport <- sdfexport %>% rename(TS17 = Candidate_TS17)
sdfexport <- sdfexport %>% rename(TS_b4 = Candidate_TS_b4)
sdfexport <- sdfexport %>% rename(TS18 = Candidate_TS18)
sdfexport <- sdfexport %>% rename(pc_bach = Perc_BachelorsDeg_and_higher)
sdfexport <- sdfexport %>% rename(PopDens = PopDens)
sdfexport <- sdfexport %>% rename(pc_Fem = perc_Fem)
sdfexport <- sdfexport %>% rename(pc_white = perc_white)
sdfexport <- sdfexport %>% rename(MedAge = MedianAge_Total)
sdfexport <- sdfexport %>% rename(Intrcpt_SE = Intercept_SE)
sdfexport <- sdfexport %>% rename(TS19b4_SE = Candidate_TS19b4_SE)
sdfexport <- sdfexport %>% rename(TS17_SE = Candidate_TS17_SE)
sdfexport <- sdfexport %>% rename(TS_b4_SE = Candidate_TS_b4_SE)
sdfexport <- sdfexport %>% rename(TS18_SE = Candidate_TS18_SE)
sdfexport <- sdfexport %>% rename(pc_bach_SE = Perc_BachelorsDeg_and_higher_SE)
sdfexport <- sdfexport %>% rename(PopDens_SE = PopDens_SE)
sdfexport <- sdfexport %>% rename(pc_Fem_SE = perc_Fem_SE)
sdfexport <- sdfexport %>% rename(pc_wht_SE = perc_white_SE)
sdfexport <- sdfexport %>% rename(MedAge_SE = MedianAge_Total_SE)
sdfexport <- sdfexport %>% rename(Intrcpt_TV = Intercept_TV)
sdfexport <- sdfexport %>% rename(TS19b4_TV = Candidate_TS19b4_TV)
sdfexport <- sdfexport %>% rename(TS17_TV = Candidate_TS17_TV)
sdfexport <- sdfexport %>% rename(TS_b4_TV = Candidate_TS_b4_TV)
sdfexport <- sdfexport %>% rename(TS18_TV = Candidate_TS18_TV)
sdfexport <- sdfexport %>% rename(pc_bach_TV = Perc_BachelorsDeg_and_higher_TV)
sdfexport <- sdfexport %>% rename(PopDens_TV = PopDens_TV)
sdfexport <- sdfexport %>% rename(pc_Fem_TV = perc_Fem_TV)
sdfexport <- sdfexport %>% rename(pc_wht_TV = perc_white_TV)
sdfexport <- sdfexport %>% rename(MedAge_TV = MedianAge_Total_TV)
sdfexport <- sdfexport %>% rename(Stud_resid = Stud_residual)
#Fields: https://github.com/cran/GWmodel/blob/master/R/gwr.basic.r


#writeOGR(sdfexport, dsn = getwd(), "NY_OUTPUT",driver="ESRI Shapefile")

```

```{r}
mypalette.6 <- brewer.pal(6, "Spectral")

map.na = list("SpatialPolygonsRescale", layout.north.arrow(),
offset = c(329000,261500), scale = 4000, col=1)
map.scale.1 = list("SpatialPolygonsRescale", layout.scale.bar(),
offset = c(326500,217000), scale = 5000, col=1, fill=c("transparent","blue"))
map.scale.2  = list("sp.text", c(326500,217900), "0", cex=0.9, col=1)
map.scale.3  = list("sp.text", c(331500,217900), "5km", cex=0.9, col=1)
map.layout <- list(map.na,map.scale.1,map.scale.2,map.scale.3)


spplot(gwr.res$SDF, "Candidate_TS19aft_u", key.space = "right", 
	main = "Basic GW regression coefficient estimates for Candidate_TS18",
	sp.layout = map.layout)

spplot(gwr.res$SDF, "Candidate_TS19aft_u", key.space = "right", 
	main = "Basic GW regression coefficient estimates for perc_white",
	sp.layout = map.layout)
```

```{r}

```


```{r SE per County}
char = "_SE"
colm = colnames(sdf@data)[grepl(char, colnames(sdf@data))]

for (i in colm)
{
print(spplot(gwr.res$SDF, i, key.space = "right", 
	main = paste("Standard Error for",i),
	sp.layout = map.layout))
  
}
tm_shape(sdf) +tm_fill(col = "Local_R2") +  tm_legend(outside = TRUE, text.size = .8)
```

```{r Coefficient_Maps}
n = 1
colm = colnames(sdf@data)[1:(n+1)]

for (i in colm)
{
val =sdf@data[,paste(i,"_TV",sep ='')]
val > -1.96
print(tm_shape(sdf) +tm_fill(col = i) + tm_legend(outside = TRUE, text.size = .8))
}
tm_shape(sdf) +tm_fill(col = "Local_R2") +  tm_legend(outside = TRUE, text.size = .8)


```



```{r}
tm_shape(sdf) +tm_fill(col = "MedianAge_Total_TV", breaks = c(-Inf, -1.96, 0, 1.96, Inf)) +  tm_legend(outside = TRUE, text.size = .8)

tm_shape(sdf) +tm_fill(col = "PopDens_TV", breaks = c(-Inf, -1.96, 0, 1.96, Inf)) +  tm_legend(outside = TRUE, text.size = .8)

tm_shape(sdf) +tm_fill(col = "perc_Fem_TV", breaks = c(-Inf, -1.96, 0, 1.96, Inf)) +  tm_legend(outside = TRUE, text.size = .8)

tm_shape(sdf) +tm_fill(col = "Perc_BachelorsDeg_and_higher_TV", breaks = c(-Inf, -1.96, 0, 1.96, Inf)) +  tm_legend(outside = TRUE, text.size = .8)

tm_shape(sdf) +tm_fill(col = "perc_white_TV", breaks = c(-Inf, -1.96, 0, 1.96, Inf)) +  tm_legend(outside = TRUE, text.size = .8)

tm_shape(sdf) +tm_fill(col = "Candidate_TS17_TV", breaks = c(-Inf, -1.96, 0, 1.96, Inf)) +  tm_legend(outside = TRUE, text.size = .8)

tm_shape(sdf) +tm_fill(col = "Candidate_TS18_TV", breaks = c(-Inf, -1.96, 0, 1.96, Inf)) +  tm_legend(outside = TRUE, text.size = .8)

tm_shape(sdf) +tm_fill(col = "Candidate_TS19b4_TV", breaks = c(-Inf, -1.96, 0, 1.96, Inf)) +  tm_legend(outside = TRUE, text.size = .8)

tm_shape(sdf) +tm_fill(col = "Candidate_TS_b4_TV", breaks = c(-Inf, -1.96, 0, 1.96, Inf)) +  tm_legend(outside = TRUE, text.size = .8)



rgwr.res <- gwr.robust(GenEl2004 ~ DiffAdd + LARent + SC1 + Unempl + PopDens + 
	Age18_24 + Age25_44 + Age45_64, data = spdf_co2, bw = bw.gwr.1,
	kernel = "bisquare", adaptive = TRUE, F123.test = TRUE)
rgwr.res

spplot(rgwr.res$SDF, "LowEduc", key.space = "right", 
	col.regions = mypalette.6, at = c(-8, -6, -4, -2, 0, 2, 4),
	main = "Robust GW regression coefficient estimates for LowEduc",
	sp.layout = map.layout)
```

```{r}
getwd()
geojson_write(sdf,geometry = "polygon",file = "output.json")
write_
```

